name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.11.0 # renovate: datasource=node depName=node

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: enable corepack
        run: corepack enable

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: enable corepack
        run: corepack enable

      - name: Installing dependencies
        run: yarn install

      - name: lint
        run: yarn prettier:check

  build:
    runs-on: ubuntu-latest
    needs: [lint]

    strategy:
      matrix:
        distro: [focal]
        arch: [x86_64]

    env:
      DISTRO: ${{ matrix.distro }} # build target, name required by binary-builder
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: binary-builder
        uses: containerbase/internal-tools@04bf0447248683c0dcffba5393594b939bfba0dc # v3.0.52
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/main'}}
          token: ${{ secrets.GITHUB_TOKEN }}
