name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.17.0 # renovate: datasource=node depName=node

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: enable corepack
        run: corepack enable

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: enable corepack
        run: corepack enable

      - name: Installing dependencies
        run: pnpm install

      - name: lint
        run: pnpm prettier

  build:
    runs-on: ubuntu-latest
    needs: [lint]

    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64

    env:
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: binary-builder
        uses: containerbase/internal-tools@67c1778f7c7b48110e8278952e08b8b71e3ccedf # v3.4.20
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/main'}}
          token: ${{ secrets.GITHUB_TOKEN }}
