name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.18.2 # renovate: datasource=node depName=node

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: enable corepack
        run: corepack enable

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: enable corepack
        run: corepack enable

      - name: Installing dependencies
        run: pnpm install

      - name: lint
        run: pnpm prettier

  build:
    needs:
      - lint
    runs-on: ${{ matrix.arch.os }}
    name: build (${{ matrix.arch.name }})

    strategy:
      matrix:
        arch:
          - name: x86_64
            os: ubuntu-24.04
          - name: aarch64
            os: ubuntu-24.04-arm

    env:
      ARCH: ${{ matrix.arch.name }} # build target, name required by binary-builder

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: binary-builder
        uses: containerbase/internal-tools@1d0c5b3aabe4a10a264d309f65ecbbd83d0e672e # v3.5.21
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/main'}}
          token: ${{ secrets.GITHUB_TOKEN }}

  success:
    runs-on: ubuntu-24.04
    needs:
      - lint
      - build
    timeout-minutes: 1
    if: always()
    steps:
      - name: Fail for failed or cancelled build
        if: |
          needs.build.result == 'failure' ||
          needs.build.result == 'cancelled'
        run: exit 1
      - name: Fail for failed or cancelled lint
        if: |
          needs.lint.result == 'failure' ||
          needs.lint.result == 'cancelled'
        run: exit 1
