name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 16.16.0 # renovate: datasource=node depName=node

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: enable corepack
        run: corepack enable

      - name: Installing dependencies
        run: yarn install

      - name: lint
        run: yarn prettier:check

  build:
    runs-on: ubuntu-latest
    needs: [lint]

    strategy:
      matrix:
        distro: [focal]
        arch: [x86_64]

    env:
      DISTRO: ${{ matrix.distro }} # build target, name required by binary-builder
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: binary-builder
        uses: renovatebot/internal-tools@f4be40361db73a5543eef5047b49b2d1143a947b # tag=v1.14.1
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/main'}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
        with:
          name: ${{ env.DISTRO }}
          path: .cache/*.tar.xz
